### ISSUE TITLE
Implement a similar meal feature

### ISSUE THREAD

**Issue by zajonc-gugle** [googleinterns/step259-2020#15]
### Description
While viewing a meal, a user should be able to ask the app for a similar meal, based on some, to be defined, recommendation algorithm.

### TODO
- [x]  frontend button sending a request and redirecting to the recommended meal's page
- [x] initial trivial backend algorithm + request handling
- [x] more sophisticated recommendation algorithm
- [x] tests

**Comment by zajonc-gugle** [comment]
@grenlayk @sandatsian feel free to use this issue to track the current state of the feature. There's an "assignees" field on the right - you can use it to track who's working on the feature at the moment.

If the state of a feature changes in some way, let's mention it in this thread.

Also, feel free to create similar issues for other features / bugs.
